export enum TransactionStatus {
  New = 'New',
  Draft = 'Draft',
  Order = 'Order',
  Posted = 'Posted',
  PostedWithLessStock = 'PostedWithLessStock',
  Completed = 'Completed',
  Closed = 'Closed',
  Approved = 'Approved',
  Archived = 'Archived',
  Canceled = 'Canceled',
  OnProcess = 'OnProcess',
  Shipped = 'Shipped',
  DeliveryConfirmed = 'DeliveryConfirmed',
  Received = 'Received',
  Refunded = 'Refunded',
}
