export const {
  ONE_HOUR,
  TWELVE_HOURS,
  BCRYPT_WORK_FACTOR,
  BCRYPT_MAX_BYTES,
  EMAIL_VERIFICATION_TIMEOUT,
  EMAIL_VERIFICATION_TOKEN_BYTES,
  EMAIL_VERIFICATION_SIGNATURE_BYTES = 45,
  PASSWORD_RESET_BYTES = 40,
  PASSWORD_RESET_TIMEOUT,
} = process.env;
